version: '3.3'

services:

  model-api:
    build: .  # use the Dockerfile from this directory (also this whole dir will be the build context)
    image: iris-model-api:dev  # image-name:version-tag
    ports:
      - '127.0.0.1:9090:5000'  # be VERY careful no to open the port to the internet (127.0.0.1 makes sure that it is only a local port)
    environment:  # environment variables (we use them in a Dockerfile and inside api.py)
      - APP_MODULE=service.api:app  # path to the 'app' object inside api.py
      - PORT=5000  # api server port inside the container, use it to expose the port above
      - WORKERS=2  # 2 workers is enough to test for multiprocessing compatibility
      - LOG_LEVEL=debug  # see all the logs available
      - MODEL_PATH=models/svm.joblib  # path to the model binary
    deploy:
      resources:  # hard system limits for the container
        limits:
          cpus: '2'
          memory: 4G  # if the app tries to use more, the container will crash and restart